### ISSUE TITLE
roadmap #

### ISSUE THREAD

**Issue by kvoistinov** [kvoistinov/test#1]
- [ ] Инициализация окна и контекста
- [ ]  Вывод треугольника
- [ ]  Загрузка текстур (TARGA)
- [ ]  Вершинный буфер
- [ ]  Шейдера
- [ ]  Ввод с клавиатуры и мыши
- [ ]  Камера
- [ ]  Blender, модель уровня, экспорт
- [ ]  Вывод уровня на экран
- [ ]  Игрок, коллизии игрока с уровнем
- [ ]  Триггеры, кнопки, лифты
- [ ]  Враги,  модели врагов (боксы)
- [ ]  Blender, оружие (пистолет), стрельба
- [ ]  ?
- [ ]  ?
- [ ]  ?
